jenkins:
  systemMessage: "CodeWizard Jenkins CASC Demo"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  remotingSecurity:
    enabled: true    
  globalCredentialsConfiguration:
    configuration:
      providerFilter: "none"
      typeFilter: "none"      
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
        - id: "dev"
          password: "dev"
  # authorizationStrategy: loggedInUsersCanDoAnything
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Job/Build:dev"
        - "Job/Cancel:dev"
        - "Job/Read:dev"
        - "Job/Workspace:dev"
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
        - "Run/Replay:dev"
        - "Run/Update:dev"

  # make sure our jenkins master has 1 executor so that we can run our pipelines
  numExecutors: 5
tool:
  git:
    installations:
      - name: Default
        home: "git"
  dockerTool:
    installations:
    - name: "Docker"
      properties:
      - installSource:
          installers:
          - fromDocker:
              version: "latest"
            
# specify the seedjob groovy script that will create the pipelines for us
jobs:
  - script: >
      folder('jenkins-labs')
  - script: >
      pipelineJob('jenkins-labs/sample-job') {
        definition {
          cps {
            script("""\
              pipeline {
                agent any
                stages {
                  stage ('test') {
                    steps {
                      echo "hello"
                    }
                  }
                }
              }""".stripIndent())
          }
        }
      }
